/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastfood.vista;
import javax.swing.JComboBox;

/**
 *
 * @author ESTUDIANTE1201T
 */
public class pedido extends javax.swing.JFrame {
    int valbeb=0;
    int valsand=0;
    int valtot=0;
  /*  int bebida;
    String sprite="$2200";
    int valSprite=2200;
    String coca = "$2800";
    int valCoca=2800;
    String quatro = "$2500";
    int valQuatro=2500;
    String jugo = "$1800";
    int valJugo=1800;
    int valBebida;
    String valTot; */
    String capSand;
    public pedido() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelBebida = new javax.swing.JLabel();
        labelSand = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelPan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelIngre = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        comboSand = new javax.swing.JComboBox<>();
        optCoca = new javax.swing.JRadioButton();
        optQuatro = new javax.swing.JRadioButton();
        optSprite = new javax.swing.JRadioButton();
        optJugo = new javax.swing.JRadioButton();
        imagen = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("SANDWICH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 270, 70, 14);

        jLabel2.setText("BEBIDA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 310, 60, 14);

        jLabel3.setText("TOTAL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 340, 50, 14);
        getContentPane().add(labelBebida);
        labelBebida.setBounds(210, 310, 50, 20);
        getContentPane().add(labelSand);
        labelSand.setBounds(210, 270, 50, 20);
        getContentPane().add(labelTotal);
        labelTotal.setBounds(210, 340, 50, 20);

        jLabel4.setText("SANDWICH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 90, 60, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fastfood/imagenes/Receipt-50.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 290, 60, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fastfood/imagenes/checked (5).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 310, 40, 30);

        jLabel7.setText("PAN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 160, 50, 14);
        getContentPane().add(labelPan);
        labelPan.setBounds(170, 160, 110, 20);

        jLabel8.setText("INGREDIENTE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 200, 80, 14);
        getContentPane().add(labelIngre);
        labelIngre.setBounds(180, 200, 110, 20);

        jLabel10.setText("NOMBRE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 130, 60, 14);
        getContentPane().add(labelNom);
        labelNom.setBounds(170, 130, 110, 0);

        comboSand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sandwich 1", "Sandwich 2", "Sandwich 3", "Sandwich  4" }));
        comboSand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSandActionPerformed(evt);
            }
        });
        getContentPane().add(comboSand);
        comboSand.setBounds(170, 90, 120, 20);

        grupo1.add(optCoca);
        optCoca.setText("CocaCola");
        optCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCocaActionPerformed(evt);
            }
        });
        getContentPane().add(optCoca);
        optCoca.setBounds(420, 80, 100, 23);

        grupo1.add(optQuatro);
        optQuatro.setText("Quatro");
        optQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optQuatroActionPerformed(evt);
            }
        });
        getContentPane().add(optQuatro);
        optQuatro.setBounds(420, 110, 100, 23);

        grupo1.add(optSprite);
        optSprite.setText("Sprite");
        optSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSpriteActionPerformed(evt);
            }
        });
        getContentPane().add(optSprite);
        optSprite.setBounds(420, 140, 100, 23);

        grupo1.add(optJugo);
        optJugo.setText("Jugo");
        optJugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optJugoActionPerformed(evt);
            }
        });
        getContentPane().add(optJugo);
        optJugo.setBounds(420, 170, 100, 23);

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fastfood/imagenes/orig_83350.jpg"))); // NOI18N
        getContentPane().add(imagen);
        imagen.setBounds(-6, -15, 660, 400);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(180, 180, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSpriteActionPerformed
       if(optSprite.isSelected())
        {
        labelBebida.setText("2200");
        valbeb=2200;
        }
    }//GEN-LAST:event_optSpriteActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        valtot=valbeb+valsand;
        String valtotS;
        valtotS=Integer.toString(valtot);
        labelTotal.setText(valtotS);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    pagos obj = new pagos();
        obj.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void optCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCocaActionPerformed
        if(optCoca.isSelected())
        {
        labelBebida.setText("2800");
        valbeb=2800;
        }
    }//GEN-LAST:event_optCocaActionPerformed

    private void optQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optQuatroActionPerformed
       if(optQuatro.isSelected())
        {
        labelBebida.setText("2500");
        valbeb=2500;
        }
    }//GEN-LAST:event_optQuatroActionPerformed

    private void optJugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optJugoActionPerformed
        if(optJugo.isSelected())
        {
        labelBebida.setText("1800");
        valbeb=1800;
        }
    }//GEN-LAST:event_optJugoActionPerformed

    private void comboSandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSandActionPerformed
        String sandwich;
        sandwich = comboSand.getSelectedItem().toString();
        if(sandwich=="Sandwich 1")
        {
        labelSand.setText("5200");
        valsand=5200;
        }
        if(sandwich=="Sandwich 2")
        {
        labelSand.setText("6500");
        valsand=6500;
        }
        if(sandwich=="Sandwich 3")
        {
        labelSand.setText("6000");
        valsand=6000;
        }
        if(sandwich=="Sandwich 4")
        {
        labelSand.setText("8500");
        valsand=8500;
        }
    }//GEN-LAST:event_comboSandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboSand;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelBebida;
    private javax.swing.JLabel labelIngre;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPan;
    private javax.swing.JLabel labelSand;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JRadioButton optCoca;
    private javax.swing.JRadioButton optJugo;
    private javax.swing.JRadioButton optQuatro;
    private javax.swing.JRadioButton optSprite;
    // End of variables declaration//GEN-END:variables
}
