/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastfood.vista;

/**
 *
 * @author ESTUDIANTE1201T
 */
public class pedido extends javax.swing.JFrame {

  /*  int bebida;
    String sprite="$2200";
    int valSprite=2200;
    String coca = "$2800";
    int valCoca=2800;
    String quatro = "$2500";
    int valQuatro=2500;
    String jugo = "$1800";
    int valJugo=1800;
    int valBebida;
    String valTot; */
    String capSand;
    public pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        optCoca = new javax.swing.JRadioButton();
        optQuatro = new javax.swing.JRadioButton();
        optSprite = new javax.swing.JRadioButton();
        optJugo = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        labelCot = new javax.swing.JLabel();
        labelPrecioBebida = new javax.swing.JLabel();
        labelBebida = new javax.swing.JLabel();
        labelSandwich = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboSandwich = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setText("SANDWICH");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 30));

        jPanel1.setMinimumSize(new java.awt.Dimension(140, 140));
        jPanel1.setLayout(null);

        jLabel5.setText("BEBIDAS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(26, 11, 65, 14);

        optCoca.setText("COCA-COLA");
        optCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCocaActionPerformed(evt);
            }
        });
        jPanel1.add(optCoca);
        optCoca.setBounds(6, 32, 100, 23);

        optQuatro.setText("QUATRO");
        optQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optQuatroActionPerformed(evt);
            }
        });
        jPanel1.add(optQuatro);
        optQuatro.setBounds(6, 58, 100, 23);

        optSprite.setText("SPRITE");
        optSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSpriteActionPerformed(evt);
            }
        });
        jPanel1.add(optSprite);
        optSprite.setBounds(6, 84, 100, 23);

        optJugo.setText("JUGO HIT");
        optJugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optJugoActionPerformed(evt);
            }
        });
        jPanel1.add(optJugo);
        optJugo.setBounds(6, 110, 100, 23);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 140, 190);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 140, 140));

        labelCot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCot.setText("Precios");
        getContentPane().add(labelCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 240, 126, 24));
        getContentPane().add(labelPrecioBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 74, 20));

        labelBebida.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelBebida.setText("BEBIDA");
        getContentPane().add(labelBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 60, -1));
        getContentPane().add(labelSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 74, 19));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setText("SANDWICH");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 275, 80, 24));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setText("TOTAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 60, -1));
        getContentPane().add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 74, 18));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fastfood/imagenes/Receipt-50.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fastfood/imagenes/checked (5).png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        comboSandwich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sandwich 1", "Sandwich 2", "Sandwich 3", "Sandwich 4" }));
        comboSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSandwichActionPerformed(evt);
            }
        });
        getContentPane().add(comboSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fastfood/imagenes/fondo.jpg"))); // NOI18N
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCocaActionPerformed
      /*  if(optCoca.isSelected()){
            labelPrecioBebida.setText(coca);

            // valTot=cocacola;
        } */
        // TODO add your handling code here:
    }//GEN-LAST:event_optCocaActionPerformed

    private void optQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optQuatroActionPerformed
     /*   if(optQuatro.isSelected()){
            labelPrecioBebida.setText(quatro);
            valBebida=valQuatro;
        } */
        // TODO add your handling code here:
    }//GEN-LAST:event_optQuatroActionPerformed

    private void optSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSpriteActionPerformed
     /*   if(optSprite.isSelected()){
            labelPrecioBebida.setText(sprite);
            valBebida=valSprite;
        }*/

        // TODO add your handling code here:
    }//GEN-LAST:event_optSpriteActionPerformed

    private void optJugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optJugoActionPerformed
      /*  if(optJugo.isSelected()){
            labelPrecioBebida.setText(jugo);
            valBebida=valJugo;
        } */
        // TODO add your handling code here:
    }//GEN-LAST:event_optJugoActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        capSand = (String) comboSandwich.getSelectedItem();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        pagos obj3= new pagos ();
        obj3.setVisible(true);

    }//GEN-LAST:event_jLabel12MouseClicked

    private void comboSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSandwichActionPerformed
        if(capSand == "Sandwich1"){
            labelSandwich.setText(capSand);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSandwichActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboSandwich;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBebida;
    private javax.swing.JLabel labelCot;
    private javax.swing.JLabel labelPrecioBebida;
    private javax.swing.JLabel labelSandwich;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JRadioButton optCoca;
    private javax.swing.JRadioButton optJugo;
    private javax.swing.JRadioButton optQuatro;
    private javax.swing.JRadioButton optSprite;
    // End of variables declaration//GEN-END:variables
}
